//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CILantro.Engine.Parser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GrammarNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GrammarNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CILantro.Engine.Parser.GrammarNames", typeof(GrammarNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssemblyAttributes.
        /// </summary>
        internal static string AssemblyAttributes {
            get {
                return ResourceManager.GetString("AssemblyAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssemblyDeclarations.
        /// </summary>
        internal static string AssemblyDeclarations {
            get {
                return ResourceManager.GetString("AssemblyDeclarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssemblyHead.
        /// </summary>
        internal static string AssemblyHead {
            get {
                return ResourceManager.GetString("AssemblyHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssemblyRefDeclarations.
        /// </summary>
        internal static string AssemblyRefDeclarations {
            get {
                return ResourceManager.GetString("AssemblyRefDeclarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssemblyRefHead.
        /// </summary>
        internal static string AssemblyRefHead {
            get {
                return ResourceManager.GetString("AssemblyRefHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallConventions.
        /// </summary>
        internal static string CallConventions {
            get {
                return ResourceManager.GetString("CallConventions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallKind.
        /// </summary>
        internal static string CallKind {
            get {
                return ResourceManager.GetString("CallKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallToken.
        /// </summary>
        internal static string CallToken {
            get {
                return ResourceManager.GetString("CallToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CilToken.
        /// </summary>
        internal static string CilToken {
            get {
                return ResourceManager.GetString("CilToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassAttributes.
        /// </summary>
        internal static string ClassAttributes {
            get {
                return ResourceManager.GetString("ClassAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassDeclaration.
        /// </summary>
        internal static string ClassDeclaration {
            get {
                return ResourceManager.GetString("ClassDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassDeclarations.
        /// </summary>
        internal static string ClassDeclarations {
            get {
                return ResourceManager.GetString("ClassDeclarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassHead.
        /// </summary>
        internal static string ClassHead {
            get {
                return ResourceManager.GetString("ClassHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassName.
        /// </summary>
        internal static string ClassName {
            get {
                return ResourceManager.GetString("ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colon.
        /// </summary>
        internal static string Colon {
            get {
                return ResourceManager.GetString("Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma.
        /// </summary>
        internal static string Comma {
            get {
                return ResourceManager.GetString("Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComplexQuotedString.
        /// </summary>
        internal static string ComplexQuotedString {
            get {
                return ResourceManager.GetString("ComplexQuotedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaration.
        /// </summary>
        internal static string Declaration {
            get {
                return ResourceManager.GetString("Declaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declarations.
        /// </summary>
        internal static string Declarations {
            get {
                return ResourceManager.GetString("Declarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dot.
        /// </summary>
        internal static string Dot {
            get {
                return ResourceManager.GetString("Dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotAssemblyToken.
        /// </summary>
        internal static string DotAssemblyToken {
            get {
                return ResourceManager.GetString("DotAssemblyToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotClassToken.
        /// </summary>
        internal static string DotClassToken {
            get {
                return ResourceManager.GetString("DotClassToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotEntrypointToken.
        /// </summary>
        internal static string DotEntrypointToken {
            get {
                return ResourceManager.GetString("DotEntrypointToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotMethodToken.
        /// </summary>
        internal static string DotMethodToken {
            get {
                return ResourceManager.GetString("DotMethodToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtendsClause.
        /// </summary>
        internal static string ExtendsClause {
            get {
                return ResourceManager.GetString("ExtendsClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExternToken.
        /// </summary>
        internal static string ExternToken {
            get {
                return ResourceManager.GetString("ExternToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImplementationAttributes.
        /// </summary>
        internal static string ImplementationAttributes {
            get {
                return ResourceManager.GetString("ImplementationAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImplementsClause.
        /// </summary>
        internal static string ImplementsClause {
            get {
                return ResourceManager.GetString("ImplementsClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction.
        /// </summary>
        internal static string Instruction {
            get {
                return ResourceManager.GetString("Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstructionInt.
        /// </summary>
        internal static string InstructionInt {
            get {
                return ResourceManager.GetString("InstructionInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstructionMethod.
        /// </summary>
        internal static string InstructionMethod {
            get {
                return ResourceManager.GetString("InstructionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstructionNone.
        /// </summary>
        internal static string InstructionNone {
            get {
                return ResourceManager.GetString("InstructionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstructionString.
        /// </summary>
        internal static string InstructionString {
            get {
                return ResourceManager.GetString("InstructionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int32Token.
        /// </summary>
        internal static string Int32Token {
            get {
                return ResourceManager.GetString("Int32Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer.
        /// </summary>
        internal static string Integer {
            get {
                return ResourceManager.GetString("Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldci40Token.
        /// </summary>
        internal static string Ldci40Token {
            get {
                return ResourceManager.GetString("Ldci40Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldci41Token.
        /// </summary>
        internal static string Ldci41Token {
            get {
                return ResourceManager.GetString("Ldci41Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldci42Token.
        /// </summary>
        internal static string Ldci42Token {
            get {
                return ResourceManager.GetString("Ldci42Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldci43Token.
        /// </summary>
        internal static string Ldci43Token {
            get {
                return ResourceManager.GetString("Ldci43Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldci44Token.
        /// </summary>
        internal static string Ldci44Token {
            get {
                return ResourceManager.GetString("Ldci44Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldci45Token.
        /// </summary>
        internal static string Ldci45Token {
            get {
                return ResourceManager.GetString("Ldci45Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldci46Token.
        /// </summary>
        internal static string Ldci46Token {
            get {
                return ResourceManager.GetString("Ldci46Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldci47Token.
        /// </summary>
        internal static string Ldci47Token {
            get {
                return ResourceManager.GetString("Ldci47Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldci48Token.
        /// </summary>
        internal static string Ldci48Token {
            get {
                return ResourceManager.GetString("Ldci48Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldci4m1AliasToken.
        /// </summary>
        internal static string Ldci4m1AliasToken {
            get {
                return ResourceManager.GetString("Ldci4m1AliasToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldci4m1Token.
        /// </summary>
        internal static string Ldci4m1Token {
            get {
                return ResourceManager.GetString("Ldci4m1Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ldci4sToken.
        /// </summary>
        internal static string Ldci4sToken {
            get {
                return ResourceManager.GetString("Ldci4sToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LdstrToken.
        /// </summary>
        internal static string LdstrToken {
            get {
                return ResourceManager.GetString("LdstrToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftBrace.
        /// </summary>
        internal static string LeftBrace {
            get {
                return ResourceManager.GetString("LeftBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftParenthesis.
        /// </summary>
        internal static string LeftParenthesis {
            get {
                return ResourceManager.GetString("LeftParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftSquareBracket.
        /// </summary>
        internal static string LeftSquareBracket {
            get {
                return ResourceManager.GetString("LeftSquareBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManagedToken.
        /// </summary>
        internal static string ManagedToken {
            get {
                return ResourceManager.GetString("ManagedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MethodAttributes.
        /// </summary>
        internal static string MethodAttributes {
            get {
                return ResourceManager.GetString("MethodAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MethodDeclaration.
        /// </summary>
        internal static string MethodDeclaration {
            get {
                return ResourceManager.GetString("MethodDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MethodDeclarations.
        /// </summary>
        internal static string MethodDeclarations {
            get {
                return ResourceManager.GetString("MethodDeclarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MethodHead.
        /// </summary>
        internal static string MethodHead {
            get {
                return ResourceManager.GetString("MethodHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MethodName.
        /// </summary>
        internal static string MethodName {
            get {
                return ResourceManager.GetString("MethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParamAttributes.
        /// </summary>
        internal static string ParamAttributes {
            get {
                return ResourceManager.GetString("ParamAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus.
        /// </summary>
        internal static string Plus {
            get {
                return ResourceManager.GetString("Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PopToken.
        /// </summary>
        internal static string PopToken {
            get {
                return ResourceManager.GetString("PopToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuotedString.
        /// </summary>
        internal static string QuotedString {
            get {
                return ResourceManager.GetString("QuotedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RetToken.
        /// </summary>
        internal static string RetToken {
            get {
                return ResourceManager.GetString("RetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RightBrace.
        /// </summary>
        internal static string RightBrace {
            get {
                return ResourceManager.GetString("RightBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RightParenthesis.
        /// </summary>
        internal static string RightParenthesis {
            get {
                return ResourceManager.GetString("RightParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RightSquareBracket.
        /// </summary>
        internal static string RightSquareBracket {
            get {
                return ResourceManager.GetString("RightSquareBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignatureArgument.
        /// </summary>
        internal static string SignatureArgument {
            get {
                return ResourceManager.GetString("SignatureArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignatureArguments0.
        /// </summary>
        internal static string SignatureArguments0 {
            get {
                return ResourceManager.GetString("SignatureArguments0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignatureArguments1.
        /// </summary>
        internal static string SignatureArguments1 {
            get {
                return ResourceManager.GetString("SignatureArguments1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SlashedName.
        /// </summary>
        internal static string SlashedName {
            get {
                return ResourceManager.GetString("SlashedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StaticToken.
        /// </summary>
        internal static string StaticToken {
            get {
                return ResourceManager.GetString("StaticToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StringToken.
        /// </summary>
        internal static string StringToken {
            get {
                return ResourceManager.GetString("StringToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeSpecification.
        /// </summary>
        internal static string TypeSpecification {
            get {
                return ResourceManager.GetString("TypeSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValuetypeToken.
        /// </summary>
        internal static string ValuetypeToken {
            get {
                return ResourceManager.GetString("ValuetypeToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoidToken.
        /// </summary>
        internal static string VoidToken {
            get {
                return ResourceManager.GetString("VoidToken", resourceCulture);
            }
        }
    }
}
